spring:
    hadoop:
        fsUri: hdfs://sandbox.hortonworks.com:8020
        resourceManagerHost: sandbox.hortonworks.com/10.0.2.15
    yarn:
        appName: yarn-calc
        applicationDir: /app/yarn-calc/
        client:
            files:
              - "file:gs-yarn-basic-dist/target/gs-yarn-basic-dist/yarn-container-0.1.0.jar"
              - "file:gs-yarn-basic-dist/target/gs-yarn-basic-dist/yarn-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: yarn-appmaster-0.1.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: yarn-container-0.1.0.jar